// CallOuts API

export const CALLOUTS_REQUEST_START = 'CALLOUTS_REQUEST_START'
export const CALLOUTS_REQUEST_SUCCESS = 'CALLOUTS_REQUEST_SUCCESS'
export const CALLOUTS_REQUEST_FAILURE = 'CALLOUTS_REQUEST_FAILURE'