// Menus API
export const MENUS_REQUEST_START = 'MENUS_REQUEST_START';
export const MENUS_REQUEST_SUCCESS = 'MENUS_REQUEST_SUCCESS';
export const MENUS_REQUEST_FAILURE = 'MENUS_REQUEST_FAILURE';


// showcase API
export const GET_SHOWCASE_INFO_START = 'GET_SHOWCASE_INFO_START';
export const GET_SHOWCASE_INFO_SUCCESS = 'GET_SHOWCASE_INFO_SUCCESS';
export const GET_SHOWCASE_INFO_FAILURE = 'GET_SHOWCASE_INFO_FAILURE';

export const GET_SHOWCASE_ENTITLED_BRANDS_START = 'GET_SHOWCASE_ENTITLED_BRANDS_START';
export const GET_SHOWCASE_ENTITLED_BRANDS_SUCCESS = 'GET_SHOWCASE_ENTITLED_BRANDS_SUCCESS';
export const GET_SHOWCASE_ENTITLED_BRANDS_FAILURE = 'GET_SHOWCASE_ENTITLED_BRANDS_FAILURE';